# Generated by Django 3.1.1 on 2020-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('us', 'US'), ('world', 'World'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('technology', 'Technology'), ('science', 'Science'), ('health', 'Health'), ('sports', 'Sports')], default='us', max_length=20)),
            ],
        ),
    ]
